### ISSUE TITLE
PXE-Service order

### ISSUE THREAD

**Issue by skrenes** [raspberrypi/rpi-eeprom#60]
I have the following `dnsmasq.conf` that network boots **both** x86 computers as well as Raspberry Pi 3B+'s. However, I recently switched to Raspberry Pi 4's with the latest firmware (pieeprom-2019-11-18.bin) and this fails.
```bash
port=0
dhcp-range=192.168.0.255,proxy
enable-tftp
tftp-root=/tftp
tftp-unique-root

# chainload to iPXE then run boot.ipxe script
dhcp-userclass=set:ipxe,iPXE
pxe-service=tag:!ipxe, x86PC, "Chainloading iPXE", ipxe.pxe
pxe-service=tag:ipxe, x86PC, "iPXE Script", boot.ipxe

# required to have the Raspberry Pi PXE boot
pxe-service=0,"Raspberry Pi Boot"

# x86 chooses first pxe-service option immediately; ignored by Raspberry Pi
pxe-prompt="PXE",0
```
If I move the "Raspberry Pi Boot" line, as in the following, the Raspberry Pi 4 boots, but the x86 machine will not (unless I remove the `pxe-prompt` line and manually select iPXE):

```bash
port=0
dhcp-range=192.168.0.255,proxy
enable-tftp
tftp-root=/tftp
tftp-unique-root

# required to have the Raspberry Pi PXE boot
pxe-service=0,"Raspberry Pi Boot"

# chainload to iPXE then run boot.ipxe script
dhcp-userclass=set:ipxe,iPXE
pxe-service=tag:!ipxe, x86PC, "Chainloading iPXE", ipxe.pxe
pxe-service=tag:ipxe, x86PC, "iPXE Script", boot.ipxe

# x86 chooses first pxe-service option immediately; ignored by Raspberry Pi
pxe-prompt="PXE",0
```

I'm currently trying to figure out if I can modify the code in such a way to get both the Raspberry Pi 4 and x86 computers to network boot automatically. But I thought I'd file a bug report since the behavior is different than Raspberry Pi 3B+.

I'm not sure which is correctly implemented, but the different behavior between the Pi 3B+ and Pi 4B merits a closer look. Thanks!

**Comment by skrenes** [comment]
I now have both x86 computers and the Pi4's booting via the following `dnsmasq.conf`:
```bash
port=0
dhcp-range=192.168.0.255,proxy
enable-tftp
tftp-root=/tftp
tftp-unique-root

# required to have the Raspberry Pi 4 network boot
dhcp-mac=set:pi,DC:A6:32:*:*:*
pxe-service=tag:pi,0,"Raspberry Pi Boot"

# chainload to iPXE then run boot.ipxe script
dhcp-userclass=set:ipxe,iPXE
pxe-service=tag:!ipxe, x86PC, "Chainloading iPXE", ipxe.pxe
pxe-service=tag:ipxe, x86PC, "iPXE Script", boot.ipxe

# x86 chooses first pxe-service option immediately; ignored by Raspberry Pi
pxe-prompt="PXE",0
```
However, my original concern regarding the differences between the Pi 3B+ and 4B remains.

**Comment by timg236** [comment]
Please can you post a wireshark capture?

**Comment by skrenes** [comment]
I haven't used wireshark in years. Are you just wanting the DNS response? If you have docker setup somewhere (perhaps on a Pi ;-)) my `Dockerfile` is as follows
```
FROM alpine:edge
RUN apk --no-cache add dnsmasq
ENTRYPOINT ["dnsmasq", "-k"]
```

My `docker-compose.yml` file is as follows:
```yaml
version: '3'
services:
  dnsmasq:
    container_name: DNSmasq
    build:
      context: .
    command: --log-facility=-
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./dnsmasq.conf:/etc/dnsmasq.conf:ro
      - ./tftp:/tftp:ro
    network_mode: host
    cap_add:
      - NET_ADMIN
    restart: always
```
